"""DeepSeek-powered C libFuzzer harness generation."""

from .artifacts import ArtifactStore, TripletArtifacts
from .compiler_validation import (BuildAdapter, CommandResult, CompilerConfig,
                                  CompilerValidator, validate_compiler)
from .fuzzer_build import (FuzzerBuildConfig, FuzzerBuildValidator,
                           DEFAULT_FUZZER_COMPILE_FLAGS,
                           DEFAULT_FUZZER_LINK_FLAGS)
from .fuzz_smoke import (LibFuzzerSmokeConfig, LibFuzzerSmokeValidator,
                         parse_final_stats)
from .feedback_loop import (FEEDBACK_LOOP_SCHEMA_VERSION, FeedbackLoopConfig,
                            FeedbackLoopResult, run_feedback_loop)
from .evaluation import (QUALITY_SIGNAL_VERSION, CrashFidelityEvaluator,
                         DeepReachabilityEvaluator, ExecutionSpeedEvaluator,
                         InputExpressivenessEvaluator, QualitySignalConfig,
                         ReplayQualityEvaluator, ResourceBoundEvaluator,
                         StaticReachabilityEvaluator, TargetIsolationEvaluator,
                         default_quality_engine, default_quality_evaluators)
from .iteration import (ITERATION_POLICY_VERSION, AggregationPolicy,
                        AutomaticFeedbackBuilder, CandidateSelector,
                        FeedbackBuilder, FeedbackDrivenIterationPlanner,
                        FeedbackItem, FeedbackPacket, IterationPlanner,
                        RegenerationRequest, ScoreCandidateSelector,
                        SelectionResult, WeightedAggregationPolicy)
from .llm import (FakeLLM, LLMClient, LLMConfig, LLMError, LLMGeneration,
                  MockLLM, OpenAICompatibleLLM, RecordedResponseLLM,
                  write_recorded_responses)
from .orchestrator import (PIPELINE_STAGES, STAGE_1_DOCS, STAGE_2_SNIPPETS,
                           STAGE_3_ROUGH, STAGE_4_HARNESS, CallableStage,
                           PipelineOrchestrator, PipelineRunResult,
                           PipelineStage, PipelineState, RollbackDecision,
                           StageContext, StageHandler, StageValidation,
                           StagedRollbackStrategy)
from .pipeline_validation import (PipelineStageValidator,
                                  PipelineValidationConfig)
from .pipeline_result import PipelineResult
from .protocol_conventions import (
    PROTOCOL_CONVENTION_SCHEMA_VERSION, ContextModel,
    ConventionInferenceResult, ProtocolConventionError, ProtocolConventions,
    SequenceModel, StatefulOperation, infer_protocol_conventions,
    parse_convention_response)
from .protocol_ir import (DEFAULT_LLM_CONFIDENCE, PROTOCOL_IR_SCHEMA_VERSION,
                          SOURCES, SOURCE_ENGINEERING, SOURCE_LLM, SOURCE_STATIC,
                          SOURCE_UNKNOWN, VARIABLE_WIDTH, FrameField, FrameModel,
                          ProtocolEvidence, ProtocolIR, ProtocolIRError)
from .protocol_miner import (PROTOCOL_MINER_SCHEMA_VERSION, ConstantFact,
                             Evidence, FieldFact, OpcodeFact, ProtocolFacts,
                             ProtocolMinerError, mine_protocol_facts,
                             mine_source_file, write_contract)
from .protocol_spec import (PROTOCOL_SPEC_SCHEMA_VERSION, ProtocolSpecError,
                            discover_protocol_spec, load_protocol_spec)
from .prompts import (PROMPT_TEMPLATES, PromptTemplate, RenderedPrompt,
                      get_prompt_template, stage1_function_doc,
                      protocol_convention_refinement,
                      stage2_structure_snippet, stage3_rough_assembly,
                      stage4_harness_plan, stage4_harness_transform)
from .runtime_validation import (RuntimeValidationResult, RuntimeValidator,
                                 classify_crash, validate_runtime)
from .sfg_adapter import (CANONICAL_NULL_NODE, SFGArtifacts, SFGGraphView,
                          SFGLoadError, SFGLoader, adapt_sfg_document,
                          is_null_node, load_sfg_artifacts,
                          normalize_null_node)
from .source_paths import SourcePathResolver
from .stage1 import (FunctionDocumentation, Stage1Error, Stage1Generator,
                     Stage1Result, generate_stage1_documentation)
from .stage2 import (Stage2Error, Stage2Generator, Stage2Result,
                     generate_stage2_snippets)
from .stage3 import (Stage2Snippet, Stage3Assembler, Stage3Error,
                     Stage3Metadata, Stage3Result, assemble_stage3,
                     load_stage2_snippets)
from .stage4 import (HarnessPlan, Stage4Error, Stage4Generator, Stage4Result,
                     generate_stage4_harness, load_protocol_contract,
                     parse_harness_plan)
from .target_build import (TargetBuildAdapter, TargetBuildConfig,
                           TargetBuildResult)
from .target_coverage import (TargetCoverageCollector, TargetCoverageConfig,
                              TargetCoverageResult, latest_target_coverage_summary,
                              target_only_summary)
from .triplet import (FunctionTriplet, TripletBypassSemantic, TripletEdge, TripletFunction,
                      load_triplets_json, stable_triplet_id, triplets_document,
                      write_triplets_json)
from .triplet_extractor import (FunctionTripletExtractionError,
                                FunctionTripletExtractor,
                                extract_function_triplets)
from .validation import (IntermediateValidator, ValidationResult,
                         validate_intermediate)

__all__ = [
    "CANONICAL_NULL_NODE",
    "ArtifactStore",
    "BuildAdapter",
    "CommandResult",
    "CompilerConfig",
    "CompilerValidator",
    "FakeLLM",
    "AggregationPolicy",
    "AutomaticFeedbackBuilder",
    "CandidateSelector",
    "FeedbackBuilder",
    "FeedbackDrivenIterationPlanner",
    "FeedbackItem",
    "FeedbackPacket",
    "FuzzerBuildConfig",
    "FuzzerBuildValidator",
    "ITERATION_POLICY_VERSION",
    "LibFuzzerSmokeConfig",
    "LibFuzzerSmokeValidator",
    "FunctionTriplet",
    "HarnessPlan",
    "FunctionTripletExtractionError",
    "FunctionTripletExtractor",
    "FunctionDocumentation",
    "DEFAULT_FUZZER_COMPILE_FLAGS",
    "DEFAULT_FUZZER_LINK_FLAGS",
    "FEEDBACK_LOOP_SCHEMA_VERSION",
    "FeedbackLoopConfig",
    "FeedbackLoopResult",
    "QUALITY_SIGNAL_VERSION",
    "QualitySignalConfig",
    "StaticReachabilityEvaluator",
    "ExecutionSpeedEvaluator",
    "ReplayQualityEvaluator",
    "InputExpressivenessEvaluator",
    "DeepReachabilityEvaluator",
    "CrashFidelityEvaluator",
    "ResourceBoundEvaluator",
    "TargetIsolationEvaluator",
    "LLMClient",
    "LLMConfig",
    "LLMError",
    "LLMGeneration",
    "IntermediateValidator",
    "IterationPlanner",
    "MockLLM",
    "OpenAICompatibleLLM",
    "PIPELINE_STAGES",
    "PROMPT_TEMPLATES",
    "PROTOCOL_CONVENTION_SCHEMA_VERSION",
    "PROTOCOL_SPEC_SCHEMA_VERSION",
    "PromptTemplate",
    "PipelineOrchestrator",
    "PipelineRunResult",
    "PipelineResult",
    "PipelineStage",
    "PipelineState",
    "PipelineStageValidator",
    "PipelineValidationConfig",
    "ProtocolConventionError",
    "ProtocolConventions",
    "ProtocolSpecError",
    "PROTOCOL_IR_SCHEMA_VERSION",
    "DEFAULT_LLM_CONFIDENCE",
    "SOURCES",
    "SOURCE_ENGINEERING",
    "SOURCE_LLM",
    "SOURCE_STATIC",
    "SOURCE_UNKNOWN",
    "VARIABLE_WIDTH",
    "FrameField",
    "FrameModel",
    "ProtocolEvidence",
    "ProtocolIR",
    "ProtocolIRError",
    "PROTOCOL_MINER_SCHEMA_VERSION",
    "ConstantFact",
    "ContextModel",
    "ConventionInferenceResult",
    "Evidence",
    "FieldFact",
    "OpcodeFact",
    "ProtocolFacts",
    "ProtocolMinerError",
    "RecordedResponseLLM",
    "RenderedPrompt",
    "RuntimeValidationResult",
    "RuntimeValidator",
    "RollbackDecision",
    "RegenerationRequest",
    "SFGArtifacts",
    "SFGGraphView",
    "SFGLoadError",
    "SFGLoader",
    "Stage1Error",
    "Stage1Generator",
    "Stage1Result",
    "StageContext",
    "StageHandler",
    "StageValidation",
    "StagedRollbackStrategy",
    "CallableStage",
    "Stage2Snippet",
    "Stage2Error",
    "Stage2Generator",
    "Stage2Result",
    "Stage3Assembler",
    "Stage3Error",
    "Stage3Metadata",
    "Stage3Result",
    "Stage4Error",
    "Stage4Generator",
    "Stage4Result",
    "StatefulOperation",
    "SourcePathResolver",
    "ScoreCandidateSelector",
    "SelectionResult",
    "SequenceModel",
    "STAGE_1_DOCS",
    "STAGE_2_SNIPPETS",
    "STAGE_3_ROUGH",
    "STAGE_4_HARNESS",
    "TargetBuildAdapter",
    "TargetBuildConfig",
    "TargetBuildResult",
    "TargetCoverageCollector",
    "TargetCoverageConfig",
    "TargetCoverageResult",
    "TripletBypassSemantic",
    "TripletEdge",
    "TripletArtifacts",
    "TripletFunction",
    "ValidationResult",
    "WeightedAggregationPolicy",
    "adapt_sfg_document",
    "assemble_stage3",
    "classify_crash",
    "discover_protocol_spec",
    "extract_function_triplets",
    "get_prompt_template",
    "generate_stage1_documentation",
    "generate_stage2_snippets",
    "generate_stage4_harness",
    "is_null_node",
    "load_sfg_artifacts",
    "load_protocol_contract",
    "load_protocol_spec",
    "load_stage2_snippets",
    "load_triplets_json",
    "latest_target_coverage_summary",
    "infer_protocol_conventions",
    "mine_protocol_facts",
    "mine_source_file",
    "normalize_null_node",
    "parse_final_stats",
    "run_feedback_loop",
    "parse_convention_response",
    "parse_harness_plan",
    "protocol_convention_refinement",
    "stage1_function_doc",
    "stage2_structure_snippet",
    "stage3_rough_assembly",
    "stage4_harness_plan",
    "stage4_harness_transform",
    "target_only_summary",
    "default_quality_engine",
    "default_quality_evaluators",
    "stable_triplet_id",
    "triplets_document",
    "validate_intermediate",
    "validate_compiler",
    "validate_runtime",
    "write_contract",
    "write_triplets_json",
    "write_recorded_responses",
]
